[build]
  base = ""
  command = "cd frontend && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18.17.0"
  REACT_APP_API_URL = "https://todo-summary-assistant-apii.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
