[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.14.0"
  CI = "false"
  REACT_APP_API_URL = "https://todo-summary-assistant-apii.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
